
services:
  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

  spring-boot-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - angular-app
