name: Continuous integration/Continuous Deployment

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
    backend-tests:
        runs-on: ubuntu-latest

        defaults:
            run:
             working-directory: back
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Java JDK
              uses: actions/setup-java@v4
              with: 
                distribution: temurin
                java-version: 21
            
            - name: Build project
              run: mvn clean install

            - name: Run tests
              run: mvn verify

            - name: Generate Jacoco reports
              run: mvn test

            - name: Upload Jacoco reports
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-reports
                path: back/target/surefire-reports/*

    frontend-tests:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: front
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Run tests
              run: npm nun test --no-watch --no-progress --browsers=ChromeHeadless

            - name: Generate Jest reports
              run: npm run test:coverage

            - name: Upload Jest reports
              uses: actions/upload-artifact@v4
              with:
                name: jest-reports
                path: front/coverage/my-app/*
